# Workflow
name: Hello

# On tells when the workflow should run
on:
  workflow_dispatch: 

# Job tells what the workflow should do, there can be one or more jobs
jobs:
  # say hello is first job (give indentation)
  say-hello:
    # creates an ephemeral container with ubuntu running
    runs-on: ubuntu-latest
    # that ephemeral container will have steps to execute, hence name those steps and use run, run has the command
    steps:
      - name: Say Hello
        run: echo "Hello User"
        
